name: List Files by PR Label

on:
  workflow_dispatch:
    inputs:
      label_name:
        description: 'Label to search for (e.g., include-in-release)'
        required: true
        default: 'include in the release'
      state:
        description: 'PR state: open, closed, or all'
        required: true
        default: 'open'

jobs:
  find-prs-and-files:
    runs-on: ubuntu-latest

    steps:
      - name: Set up jq and curl
        run: sudo apt-get install -y jq

      - name: Find PRs by label and list unique files
        run: |
          echo "Searching PRs with label '${{ github.event.inp
